on:
  pull_request:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - run: curl -fsSL https://raw.githubusercontent.com/mviereck/x11docker/v7.6.0/x11docker | sudo bash -s -- --update
      - run: ./test.sh --xvfb
      - uses: actions/upload-artifact@v4
        with:
          path: x11docker.log
          name: x11docker.log
